export const translateLocation = (location, lang) => {
  const map = {
    'An Giang': { vi: 'An Giang', en: 'An Giang' },
    'Bà Rịa - Vũng Tàu': { vi: 'Bà Rịa - Vũng Tàu', en: 'Ba Ria - Vung Tau' },
    'Bắc Giang': { vi: 'Bắc Giang', en: 'Bac Giang' },
    'Bắc Kạn': { vi: 'Bắc Kạn', en: 'Bac Kan' },
    'Bạc Liêu': { vi: 'Bạc Liêu', en: 'Bac Lieu' },
    'Bắc Ninh': { vi: 'Bắc Ninh', en: 'Bac Ninh' },
    'Bến Tre': { vi: 'Bến Tre', en: 'Ben Tre' },
    'Bình Định': { vi: 'Bình Định', en: 'Binh Dinh' },
    'Bình Dương': { vi: 'Bình Dương', en: 'Binh Duong' },
    'Bình Phước': { vi: 'Bình Phước', en: 'Binh Phuoc' },
    'Bình Thuận': { vi: 'Bình Thuận', en: 'Binh Thuan' },
    'Cà Mau': { vi: 'Cà Mau', en: 'Ca Mau' },
    'Thành phố Cần Thơ': { vi: 'Cần Thơ', en: 'Can Tho' },
    'Cao Bằng': { vi: 'Cao Bằng', en: 'Cao Bang' },
    'Đà Nẵng': { vi: 'Đà Nẵng', en: 'Da Nang' },
    'Đắk Lắk': { vi: 'Đắk Lắk', en: 'Dak Lak' },
    'Đắk Nông': { vi: 'Đắk Nông', en: 'Dak Nong' },
    'Điện Biên': { vi: 'Điện Biên', en: 'Dien Bien' },
    'Đồng Nai': { vi: 'Đồng Nai', en: 'Dong Nai' },
    'Đồng Tháp': { vi: 'Đồng Tháp', en: 'Dong Thap' },
    'Gia Lai': { vi: 'Gia Lai', en: 'Gia Lai' },
    'Hà Giang': { vi: 'Hà Giang', en: 'Ha Giang' },
    'Hà Nam': { vi: 'Hà Nam', en: 'Ha Nam' },
    'Hà Nội': { vi: 'Hà Nội', en: 'Hanoi' },
    'Hà Tĩnh': { vi: 'Hà Tĩnh', en: 'Ha Tinh' },
    'Hải Dương': { vi: 'Hải Dương', en: 'Hai Duong' },
    'Hải Phòng': { vi: 'Hải Phòng', en: 'Hai Phong' },
    'Hậu Giang': { vi: 'Hậu Giang', en: 'Hau Giang' },
    'Hòa Bình': { vi: 'Hòa Bình', en: 'Hoa Binh' },
    'Hưng Yên': { vi: 'Hưng Yên', en: 'Hung Yen' },
    'Khánh Hòa': { vi: 'Khánh Hòa', en: 'Khanh Hoa' },
    'Kiên Giang': { vi: 'Kiên Giang', en: 'Kien Giang' },
    'Kon Tum': { vi: 'Kon Tum', en: 'Kon Tum' },
    'Lai Châu': { vi: 'Lai Châu', en: 'Lai Chau' },
    'Lâm Đồng': { vi: 'Lâm Đồng', en: 'Lam Dong' },
    'Lạng Sơn': { vi: 'Lạng Sơn', en: 'Lang Son' },
    'Lào Cai': { vi: 'Lào Cai', en: 'Lao Cai' },
    'Long An': { vi: 'Long An', en: 'Long An' },
    'Nam Định': { vi: 'Nam Định', en: 'Nam Dinh' },
    'Nghệ An': { vi: 'Nghệ An', en: 'Nghe An' },
    'Ninh Bình': { vi: 'Ninh Bình', en: 'Ninh Binh' },
    'Ninh Thuận': { vi: 'Ninh Thuận', en: 'Ninh Thuan' },
    'Phú Thọ': { vi: 'Phú Thọ', en: 'Phu Tho' },
    'Phú Yên': { vi: 'Phú Yên', en: 'Phu Yen' },
    'Quảng Bình': { vi: 'Quảng Bình', en: 'Quang Binh' },
    'Quảng Nam': { vi: 'Quảng Nam', en: 'Quang Nam' },
    'Quảng Ngãi': { vi: 'Quảng Ngãi', en: 'Quang Ngai' },
    'Quảng Ninh': { vi: 'Quảng Ninh', en: 'Quang Ninh' },
    'Quảng Trị': { vi: 'Quảng Trị', en: 'Quang Tri' },
    'Sóc Trăng': { vi: 'Sóc Trăng', en: 'Soc Trang' },
    'Sơn La': { vi: 'Sơn La', en: 'Son La' },
    'Tây Ninh': { vi: 'Tây Ninh', en: 'Tay Ninh' },
    'Thái Bình': { vi: 'Thái Bình', en: 'Thai Binh' },
    'Thái Nguyên': { vi: 'Thái Nguyên', en: 'Thai Nguyen' },
    'Thanh Hóa': { vi: 'Thanh Hóa', en: 'Thanh Hoa' },
    'Thừa Thiên Huế': { vi: 'Thừa Thiên Huế', en: 'Thua Thien Hue' },
    'Tiền Giang': { vi: 'Tiền Giang', en: 'Tien Giang' },
    'TP. Hồ Chí Minh': { vi: 'TP. Hồ Chí Minh', en: 'Ho Chi Minh City' },
    'Trà Vinh': { vi: 'Trà Vinh', en: 'Tra Vinh' },
    'Tuyên Quang': { vi: 'Tuyên Quang', en: 'Tuyen Quang' },
    'Vĩnh Long': { vi: 'Vĩnh Long', en: 'Vinh Long' },
    'Vĩnh Phúc': { vi: 'Vĩnh Phúc', en: 'Vinh Phuc' },
    'Yên Bái': { vi: 'Yên Bái', en: 'Yen Bai' },
  };

  const key = Object.keys(map).find((k) => location?.includes(k));
  return key ? map[key][lang] : location;
};
