# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main", "feature"]
  pull_request:
    branches: ["main", "feature"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Setup Node.js for matrix version
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # Install dependencies for backend
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      # Install dependencies for frontend
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      # Build and start backend
      - name: Start backend server
        working-directory: ./backend
        run: npm start &

      # Build and start frontend
      - name: Start frontend client
        working-directory: ./frontend
        run: npm run dev &

    # Run tests (optional)
    # - name: Run tests
    #   run: npm test
